export const ALL_DETAILS_REQUEST = "ALL_DETAILS_REQUEST"
export const ALL_DETAILS_SUCCESS = "ALL_DETAILS_SUCCESS"
export const ALL_DETAILS_FAIL = "ALL_DETAILS_FAIL"

export const NEW_DETAILS_REQUEST = "NEW_DETAILS_REQUEST"
export const NEW_DETAILS_SUCCESS = "NEW_DETAILS_SUCCESS"
export const NEW_DETAILS_FAIL = "NEW_DETAILS_FAIL"
export const NEW_DETAILS_RESET = "NEW_DETAILS_RESET"

export const COMPANY_DETAILS_REQUEST = "COMPANY_DETAILS_REQUEST"
export const COMPANY_DETAILS_SUCCESS = "COMPANY_DETAILS_SUCCESS"
export const COMPANY_DETAILS_FAIL = "COMPANY_DETAILS_FAIL"


export const COMPANY_CREATE_REQUEST = "COMPANY_CREATE_REQUEST"
export const COMPANY_CREATE_SUCCESS = "COMPANY_CREATE_SUCCESS"
export const COMPANY_CREATE_FAIL = "COMPANY_CREATE_FAIL"
export const COMPANY_CREATE_RESET = "COMPANY_CREATE_RESET"

export const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_DETAIL"
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS"
export const UPDATE_COMPANY_FAIL = "UPDATE_COMPANY_FAIL"
export const UPDATE_COMPANY_RESET = "UPDATE_COMPANY_RESET"

export const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_DETAIL"
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS"
export const DELETE_COMPANY_FAIL = "DELETE_COMPANY_FAIL"
export const DELETE_COMPANY_RESET = "DELETE_COMPANY_RESET"

export const CLEAR_ERROS = "CLEAR_ERROS"